version: "3.7"
services:  
  consul:
    image: consul
    hostname: "{{.Node.Hostname}}"
    networks:
      - rabbitcloud
      - rabbitfog
      - rabbitedge
      - consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:53
    deploy:
      mode: global
      #replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    # command: [ "agent", "-server", "-bootstrap-expect=1", "-retry-max=3", "-retry-interval=10s", "-datacenter=iiot", "-join=consul", "-retry-join=consul", "-bind={{ GetInterfaceIP \"eth0\" }}", "-client=0.0.0.0", "-ui"]
    command: [ "agent", "-server", "-bootstrap-expect=3", "-retry-max=3", "-retry-interval=10s", "-datacenter=iiot", "-join=consul", "-retry-join=consul", "-bind={{ GetInterfaceIP \"eth0\" }}", "-client=0.0.0.0", "-ui"]

networks: 
  rabbitcloud:
    external: true
  rabbitfog:
    external: true
  rabbitedge:
    external: true
  consul:
    external: true